TRUNCATE TABLE STAGING.ACCT_STG
GO 

BULK INSERT STAGING.SCORES_STG FROM '<Path>\acct_stg.csv'
WITH (
    CHECK_CONSTRAINTS,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    KEEPIDENTITY,
    TABLOCK
)
GO

TRUNCATE TABLE STAGING.CLIENT_STG
GO 

BULK INSERT STAGING.CLIENT_STG FROM '<Path>\client_stg.csv'
WITH (
    CHECK_CONSTRAINTS,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    KEEPIDENTITY,
    TABLOCK
)
GO

TRUNCATE TABLE STAGING.KPI_LIST_STG
GO 

BULK INSERT STAGING.KPI_LIST_STG FROM '<Path>\kpi_list_stg.csv'
WITH (
    CHECK_CONSTRAINTS,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    KEEPIDENTITY,
    TABLOCK
)
GO

TRUNCATE TABLE STAGING.ORG_UNIT_STG
GO 

BULK INSERT STAGING.ORG_UNIT_STG FROM '<Path>\org_unit_stg.csv'
WITH (
    CHECK_CONSTRAINTS,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    KEEPIDENTITY,
    TABLOCK
)
GO

TRUNCATE TABLE STAGING.RM_STG
GO 

BULK INSERT STAGING.RM_STG FROM '<Path>\rm_stg.csv'
WITH (
    CHECK_CONSTRAINTS,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    KEEPIDENTITY,
    TABLOCK
)
GO


TRUNCATE TABLE STAGING.SCORES_STG
GO 

BULK INSERT STAGING.SCORES_STG FROM '<Path>\scores_stg.csv'
WITH (
    CHECK_CONSTRAINTS,
    FIELDTERMINATOR=',',
    ROWTERMINATOR='\n',
    KEEPIDENTITY,
    TABLOCK
)
GO
